name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
        #   pip install -r requirements.txt
        # TODO: Uncomment once we add tests
        # - name: Test with pytest
        #   run: pytest src/tests/ --doctest-modules --junitxml=junit/test-results-3.12.xml
        # - name: Upload pytest test results
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: pytest-results-3.12
        #     path: junit/test-results-3.12.xml
        #   # Use always() to always run this step to publish test results when there are test failures
        #   if: ${{ always() }}